### ISSUE TITLE
Starting SimHub w/ MIDIiothrows an exception

### ISSUE THREAD

**Issue by nveeser** [blekenbleu/MIDIio#3]
Got an exception from SubHub on startup now

SimHub seems to have log4net 2.0.8 installed rather than 2.0.15?

---------------------------

---------------------------
An error occured while loading plugin blekenbleu.MIDIio : System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=2.0.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

File name: 'log4net, Version=2.0.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'

   at blekenbleu.MIDIio.Log(Byte level, String str)

   at blekenbleu.MIDIio.Init(PluginManager pluginManager)

   at SimHub.Plugins.PluginManager.<InitPluginManager>d__48.MoveNext()

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

---------------------------
OK   
---------------------------

**Comment by blekenbleu** [comment]
SimHub 9.3.6 has log4net.dll 2.0.15-NET 4.5:
![log4net](https://github.com/user-attachments/assets/9ea279bd-9ffd-4eeb-bf8b-02d5af669b57)

**Comment by nveeser** [comment]
Needed upgrade SimHub from 8.X to 9.X. Thanks that fixed it

**Comment by blekenbleu** [comment]
Thanks for confirmation;  Note added to ReadMe.  `32ae01f`
